#!/bin/sh

echo Chain 2 from zipped binary link to referal
echo Args: $@
echo 'UPGRADE "chain3" NEEDED at height 936: {"binaries": {"linux/amd64": "https://github.com/regen-network/cosmos-upgrade-manager/raw/auto-download/testdata/repo/ref_zipped?checksum=sha256:e31221befd221c71f8ae8273728b7474b5f50dd6acb30db735a67e57ff13bc44"}}'
sleep 2
