#!/bin/sh

echo Chain 2 from zipped binary link to referal
echo Args: $@
echo 'UPGRADE "chain3" NEEDED at height 936: {"binaries": {"linux/amd64": "https://github.com/regen-network/cosmos-upgrade-manager/raw/auto-download/testdata/repo/ref_zipped?checksum=sha256:59708d1142dfd3f9d6ffafecd7f89c641d982c9d5d999d86b211a1a736f114ad"}}'
sleep 2
